version: "3"
services:
  mongo:
    container_name: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    tty: true
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
